---
services:
  auth-api:
    container_name: auth-api
    restart: always
    build:
      dockerfile: Dockerfile
    image: auth-api:latest
    environment:
      PROFILE: prod
      JWT_SECRET: world
      ACCESS_TOKEN: world
    ports:
      - "8080:8080"
